version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tgbot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 10
  bot:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      PUBLIC_BASE_URL: ${PUBLIC_BASE_URL}
      OPENROUTER_REFERRER: ${OPENROUTER_REFERRER}
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      DB_DSN: postgresql+asyncpg://user:pass@db:5432/tgbot
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      LOG_LEVEL: INFO
      AUTO_MESSAGES_DEFAULT: ${AUTO_MESSAGES_DEFAULT:-true}
      PROACTIVE_MIN_SECONDS: ${PROACTIVE_MIN_SECONDS:-3600}
      PROACTIVE_MAX_SECONDS: ${PROACTIVE_MAX_SECONDS:-7200}
      REPLY_DELAY_MIN_SECONDS: ${REPLY_DELAY_MIN_SECONDS:-5}
      REPLY_DELAY_MAX_SECONDS: ${REPLY_DELAY_MAX_SECONDS:-10}
      USER_MIN_SECONDS_BETWEEN_MSG: ${USER_MIN_SECONDS_BETWEEN_MSG:-5}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

